apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-container
        image: tmdwn0704/all-in-one-product:1.0
        command: ["/bin/sh", "-c"]
        args:
        - ./wait-for-it.sh product-db.default.svc:3306 -t 0;
          python3 manage.py makemigrations item;
          python3 manage.py migrate;
          python3 manage.py loaddata item/fixtures/data.json;
          python3 manage.py runserver 0.0.0.0:8000;
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: product-url
        - configMapRef:
            name: product-db

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 2

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: product-db
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: product-db
              key: MYSQL_DB             
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: product-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: product-volume
        emptyDir: {}
        ## TODO: storage class
        # persistentVolumeClaim:
        #   claimName:  product-pvc
