name: image-build-and-update

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_REPO: public.ecr.aws/x4j4s8t3
  APP_NAME: all-in-one-product
  CHART_NAME: product
  MANIFEST_REPO_DIR: manifest
  BASE_REPO_DIR: main
  MANIFEST_REPO: sjoh0704/All-In-One
  AWS_DEFAULT_REGION: ap-northeast-2


permissions:
  id-token: write
  contents: read

jobs:
## build-image
  build-image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout 
      uses: actions/checkout@v2
      with:
        path: ${{ env.BASE_REPO_DIR }}

    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::225920063910:role/ecr-git-action
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
    
    - name: Build, tag, and push image to Amazon ECR
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $IMAGE_REPO
        docker build -t $IMAGE_REPO/$APP_NAME:latest ./$BASE_REPO_DIR
        docker tag $IMAGE_REPO/$APP_NAME:latest $IMAGE_REPO/$APP_NAME:$RELEASE_VERSION
        docker push $IMAGE_REPO/$APP_NAME:latest
        docker push $IMAGE_REPO/$APP_NAME:$RELEASE_VERSION


## update manifest
  update-manifest:
    runs-on: ubuntu-latest
    needs: build-image
    steps: 

    - name: Checkout 
      uses: actions/checkout@v2
      with:
        repository: sjoh0704/All-In-One
        ref: "master"
        path: ${{ env.MANIFEST_REPO_DIR }}
        persist-credentials: false
        
    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: update manifest
      run: |
        sed -i '/^  repository:/c\  repository: ${{ env.IMAGE_REPO }}' $MANIFEST_REPO_DIR/chart/$CHART_NAME/values.yaml
        sed -i '/^  registry:/c\  registry: ${{ env.APP_NAME }}' $MANIFEST_REPO_DIR/chart/$CHART_NAME/values.yaml
        sed -i '/^  tag:/c\  tag: ${{ env.RELEASE_VERSION }}' $MANIFEST_REPO_DIR/chart/$CHART_NAME/values.yaml

    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: 'chart/${{ env.CHART_NAME }}/values.yaml'
        ref: "master"
        cwd: "./${{ env.MANIFEST_REPO_DIR }}"

    - name: Push commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        branch: "master"
        force: true
        repository: "${{ env.MANIFEST_REPO }}"
        directory: "./${{ env.MANIFEST_REPO_DIR }}"


